package lime;


import lime.utils.Assets;


class AssetData {

	private static var initialized:Bool = false;
	
	public static var library = new #if haxe3 Map <String, #else Hash <#end LibraryType> ();
	public static var path = new #if haxe3 Map <String, #else Hash <#end String> ();
	public static var type = new #if haxe3 Map <String, #else Hash <#end AssetType> ();	
	
	public static function initialize():Void {
		
		if (!initialized) {
			
			path.set ("assets/1.png", "assets/1.png");
			type.set ("assets/1.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/2.png", "assets/2.png");
			type.set ("assets/2.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/3.png", "assets/3.png");
			type.set ("assets/3.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/4.png", "assets/4.png");
			type.set ("assets/4.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/Background1.png", "assets/Background1.png");
			type.set ("assets/Background1.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/Background2 (1).png", "assets/Background2 (1).png");
			type.set ("assets/Background2 (1).png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/Background2.png", "assets/Background2.png");
			type.set ("assets/Background2.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/Background4.png", "assets/Background4.png");
			type.set ("assets/Background4.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/Bomb.png", "assets/Bomb.png");
			type.set ("assets/Bomb.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/bosssheet.png", "assets/bosssheet.png");
			type.set ("assets/bosssheet.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/bosssheet2.png", "assets/bosssheet2.png");
			type.set ("assets/bosssheet2.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/buttonsmedium2.png", "assets/buttonsmedium2.png");
			type.set ("assets/buttonsmedium2.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/Coin1.png", "assets/Coin1.png");
			type.set ("assets/Coin1.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/contestsprite.png", "assets/contestsprite.png");
			type.set ("assets/contestsprite.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/fireball.png", "assets/fireball.png");
			type.set ("assets/fireball.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/Game-Over.png", "assets/Game-Over.png");
			type.set ("assets/Game-Over.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/images/images-go-here.txt", "assets/images/images-go-here.txt");
			type.set ("assets/images/images-go-here.txt", Reflect.field (AssetType, "text".toUpperCase ()));
			path.set ("assets/Map1.png", "assets/Map1.png");
			type.set ("assets/Map1.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/Map2.png", "assets/Map2.png");
			type.set ("assets/Map2.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/Map3.png", "assets/Map3.png");
			type.set ("assets/Map3.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/mapCSV_Group1_zombies.csv", "assets/mapCSV_Group1_zombies.csv");
			type.set ("assets/mapCSV_Group1_zombies.csv", Reflect.field (AssetType, "text".toUpperCase ()));
			path.set ("assets/Maps0037.png", "assets/Maps0037.png");
			type.set ("assets/Maps0037.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/Maps0038.png", "assets/Maps0038.png");
			type.set ("assets/Maps0038.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/Maps0039.png", "assets/Maps0039.png");
			type.set ("assets/Maps0039.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/Maps0040.png", "assets/Maps0040.png");
			type.set ("assets/Maps0040.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/Maps0041.png", "assets/Maps0041.png");
			type.set ("assets/Maps0041.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/Maps0042.png", "assets/Maps0042.png");
			type.set ("assets/Maps0042.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/Maps0043.png", "assets/Maps0043.png");
			type.set ("assets/Maps0043.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/MoGames.png", "assets/MoGames.png");
			type.set ("assets/MoGames.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/music/music-goes-here.txt", "assets/music/music-goes-here.txt");
			type.set ("assets/music/music-goes-here.txt", Reflect.field (AssetType, "text".toUpperCase ()));
			path.set ("assets/newerbuttons26.png", "assets/newerbuttons26.png");
			type.set ("assets/newerbuttons26.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/pauselayer.png", "assets/pauselayer.png");
			type.set ("assets/pauselayer.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/R1.png", "assets/R1.png");
			type.set ("assets/R1.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/R2.png", "assets/R2.png");
			type.set ("assets/R2.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/R3.png", "assets/R3.png");
			type.set ("assets/R3.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/robotcloud.png", "assets/robotcloud.png");
			type.set ("assets/robotcloud.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/robotcloud120x120.png", "assets/robotcloud120x120.png");
			type.set ("assets/robotcloud120x120.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/scene1.png", "assets/scene1.png");
			type.set ("assets/scene1.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/scene2-1.png", "assets/scene2-1.png");
			type.set ("assets/scene2-1.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/scene2-2.png", "assets/scene2-2.png");
			type.set ("assets/scene2-2.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/scene2-3.png", "assets/scene2-3.png");
			type.set ("assets/scene2-3.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/scene2.png", "assets/scene2.png");
			type.set ("assets/scene2.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/scene3-1.png", "assets/scene3-1.png");
			type.set ("assets/scene3-1.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/scene3-2.png", "assets/scene3-2.png");
			type.set ("assets/scene3-2.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/Shotgun49x12.png", "assets/Shotgun49x12.png");
			type.set ("assets/Shotgun49x12.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/sounds/BG sound in loop maybe.mp3", "assets/sounds/BG sound in loop maybe.mp3");
			type.set ("assets/sounds/BG sound in loop maybe.mp3", Reflect.field (AssetType, "music".toUpperCase ()));
			path.set ("assets/sounds/Decisions.mp3", "assets/sounds/Decisions.mp3");
			type.set ("assets/sounds/Decisions.mp3", Reflect.field (AssetType, "music".toUpperCase ()));
			path.set ("assets/sounds/grenade.wav", "assets/sounds/grenade.wav");
			type.set ("assets/sounds/grenade.wav", Reflect.field (AssetType, "sound".toUpperCase ()));
			path.set ("assets/sounds/gun.wav", "assets/sounds/gun.wav");
			type.set ("assets/sounds/gun.wav", Reflect.field (AssetType, "sound".toUpperCase ()));
			path.set ("assets/sounds/shotgun.wav", "assets/sounds/shotgun.wav");
			type.set ("assets/sounds/shotgun.wav", Reflect.field (AssetType, "sound".toUpperCase ()));
			path.set ("assets/sounds/sounds-go-here.txt", "assets/sounds/sounds-go-here.txt");
			type.set ("assets/sounds/sounds-go-here.txt", Reflect.field (AssetType, "text".toUpperCase ()));
			path.set ("assets/sounds/What You Want ver 2.mp3", "assets/sounds/What You Want ver 2.mp3");
			type.set ("assets/sounds/What You Want ver 2.mp3", Reflect.field (AssetType, "music".toUpperCase ()));
			path.set ("assets/Sprites (1).png", "assets/Sprites (1).png");
			type.set ("assets/Sprites (1).png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/Title (1).png", "assets/Title (1).png");
			type.set ("assets/Title (1).png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/Upgrades0019.png", "assets/Upgrades0019.png");
			type.set ("assets/Upgrades0019.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/Upgrades0020.png", "assets/Upgrades0020.png");
			type.set ("assets/Upgrades0020.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/Upgrades0021.png", "assets/Upgrades0021.png");
			type.set ("assets/Upgrades0021.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/Upgrades0023.png", "assets/Upgrades0023.png");
			type.set ("assets/Upgrades0023.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/Upgrades0024.png", "assets/Upgrades0024.png");
			type.set ("assets/Upgrades0024.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/Upgrades320023.png", "assets/Upgrades320023.png");
			type.set ("assets/Upgrades320023.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/Upgrades500019.png", "assets/Upgrades500019.png");
			type.set ("assets/Upgrades500019.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/Upgrades500020.png", "assets/Upgrades500020.png");
			type.set ("assets/Upgrades500020.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/Upgrades500021.png", "assets/Upgrades500021.png");
			type.set ("assets/Upgrades500021.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/Upgrades500023.png", "assets/Upgrades500023.png");
			type.set ("assets/Upgrades500023.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/Upgrades500024.png", "assets/Upgrades500024.png");
			type.set ("assets/Upgrades500024.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/zombieblood.png", "assets/zombieblood.png");
			type.set ("assets/zombieblood.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/zombiecar.png", "assets/zombiecar.png");
			type.set ("assets/zombiecar.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/Zombiegirl1.png", "assets/Zombiegirl1.png");
			type.set ("assets/Zombiegirl1.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/zombiegirl2.png", "assets/zombiegirl2.png");
			type.set ("assets/zombiegirl2.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/zombiegirl3.png", "assets/zombiegirl3.png");
			type.set ("assets/zombiegirl3.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/zombieguy1.png", "assets/zombieguy1.png");
			type.set ("assets/zombieguy1.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/zombieguy2.png", "assets/zombieguy2.png");
			type.set ("assets/zombieguy2.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/zombieguy3.png", "assets/zombieguy3.png");
			type.set ("assets/zombieguy3.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/zombieguy4.png", "assets/zombieguy4.png");
			type.set ("assets/zombieguy4.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/Zombiehunter.png", "assets/Zombiehunter.png");
			type.set ("assets/Zombiehunter.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/zombiemap.png", "assets/zombiemap.png");
			type.set ("assets/zombiemap.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/sounds/beep.ogg", "assets/sounds/beep.ogg");
			type.set ("assets/sounds/beep.ogg", Reflect.field (AssetType, "sound".toUpperCase ()));
			path.set ("assets/sounds/flixel.ogg", "assets/sounds/flixel.ogg");
			type.set ("assets/sounds/flixel.ogg", Reflect.field (AssetType, "sound".toUpperCase ()));
			path.set ("assets/fonts/nokiafc22.ttf", "assets/fonts/nokiafc22.ttf");
			type.set ("assets/fonts/nokiafc22.ttf", Reflect.field (AssetType, "font".toUpperCase ()));
			path.set ("assets/fonts/arial.ttf", "assets/fonts/arial.ttf");
			type.set ("assets/fonts/arial.ttf", Reflect.field (AssetType, "font".toUpperCase ()));
			path.set ("flixel/flixel-ui/img/box.png", "flixel/flixel-ui/img/box.png");
			type.set ("flixel/flixel-ui/img/box.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("flixel/flixel-ui/img/button.png", "flixel/flixel-ui/img/button.png");
			type.set ("flixel/flixel-ui/img/button.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("flixel/flixel-ui/img/button_arrow_down.png", "flixel/flixel-ui/img/button_arrow_down.png");
			type.set ("flixel/flixel-ui/img/button_arrow_down.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("flixel/flixel-ui/img/button_arrow_left.png", "flixel/flixel-ui/img/button_arrow_left.png");
			type.set ("flixel/flixel-ui/img/button_arrow_left.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("flixel/flixel-ui/img/button_arrow_right.png", "flixel/flixel-ui/img/button_arrow_right.png");
			type.set ("flixel/flixel-ui/img/button_arrow_right.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("flixel/flixel-ui/img/button_arrow_up.png", "flixel/flixel-ui/img/button_arrow_up.png");
			type.set ("flixel/flixel-ui/img/button_arrow_up.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("flixel/flixel-ui/img/button_thin.png", "flixel/flixel-ui/img/button_thin.png");
			type.set ("flixel/flixel-ui/img/button_thin.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("flixel/flixel-ui/img/button_toggle.png", "flixel/flixel-ui/img/button_toggle.png");
			type.set ("flixel/flixel-ui/img/button_toggle.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("flixel/flixel-ui/img/check_box.png", "flixel/flixel-ui/img/check_box.png");
			type.set ("flixel/flixel-ui/img/check_box.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("flixel/flixel-ui/img/check_mark.png", "flixel/flixel-ui/img/check_mark.png");
			type.set ("flixel/flixel-ui/img/check_mark.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("flixel/flixel-ui/img/chrome.png", "flixel/flixel-ui/img/chrome.png");
			type.set ("flixel/flixel-ui/img/chrome.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("flixel/flixel-ui/img/chrome_flat.png", "flixel/flixel-ui/img/chrome_flat.png");
			type.set ("flixel/flixel-ui/img/chrome_flat.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("flixel/flixel-ui/img/chrome_inset.png", "flixel/flixel-ui/img/chrome_inset.png");
			type.set ("flixel/flixel-ui/img/chrome_inset.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("flixel/flixel-ui/img/chrome_light.png", "flixel/flixel-ui/img/chrome_light.png");
			type.set ("flixel/flixel-ui/img/chrome_light.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("flixel/flixel-ui/img/dropdown_mark.png", "flixel/flixel-ui/img/dropdown_mark.png");
			type.set ("flixel/flixel-ui/img/dropdown_mark.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("flixel/flixel-ui/img/finger_big.png", "flixel/flixel-ui/img/finger_big.png");
			type.set ("flixel/flixel-ui/img/finger_big.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("flixel/flixel-ui/img/finger_small.png", "flixel/flixel-ui/img/finger_small.png");
			type.set ("flixel/flixel-ui/img/finger_small.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("flixel/flixel-ui/img/hilight.png", "flixel/flixel-ui/img/hilight.png");
			type.set ("flixel/flixel-ui/img/hilight.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("flixel/flixel-ui/img/invis.png", "flixel/flixel-ui/img/invis.png");
			type.set ("flixel/flixel-ui/img/invis.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("flixel/flixel-ui/img/minus_mark.png", "flixel/flixel-ui/img/minus_mark.png");
			type.set ("flixel/flixel-ui/img/minus_mark.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("flixel/flixel-ui/img/plus_mark.png", "flixel/flixel-ui/img/plus_mark.png");
			type.set ("flixel/flixel-ui/img/plus_mark.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("flixel/flixel-ui/img/radio.png", "flixel/flixel-ui/img/radio.png");
			type.set ("flixel/flixel-ui/img/radio.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("flixel/flixel-ui/img/radio_dot.png", "flixel/flixel-ui/img/radio_dot.png");
			type.set ("flixel/flixel-ui/img/radio_dot.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("flixel/flixel-ui/img/swatch.png", "flixel/flixel-ui/img/swatch.png");
			type.set ("flixel/flixel-ui/img/swatch.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("flixel/flixel-ui/img/tab.png", "flixel/flixel-ui/img/tab.png");
			type.set ("flixel/flixel-ui/img/tab.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("flixel/flixel-ui/img/tab_back.png", "flixel/flixel-ui/img/tab_back.png");
			type.set ("flixel/flixel-ui/img/tab_back.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("flixel/flixel-ui/img/tooltip_arrow.png", "flixel/flixel-ui/img/tooltip_arrow.png");
			type.set ("flixel/flixel-ui/img/tooltip_arrow.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("flixel/flixel-ui/xml/defaults.xml", "flixel/flixel-ui/xml/defaults.xml");
			type.set ("flixel/flixel-ui/xml/defaults.xml", Reflect.field (AssetType, "text".toUpperCase ()));
			path.set ("flixel/flixel-ui/xml/default_loading_screen.xml", "flixel/flixel-ui/xml/default_loading_screen.xml");
			type.set ("flixel/flixel-ui/xml/default_loading_screen.xml", Reflect.field (AssetType, "text".toUpperCase ()));
			path.set ("flixel/flixel-ui/xml/default_popup.xml", "flixel/flixel-ui/xml/default_popup.xml");
			type.set ("flixel/flixel-ui/xml/default_popup.xml", Reflect.field (AssetType, "text".toUpperCase ()));
			
			
			initialized = true;
			
		} //!initialized
		
	} //initialize
	
	
} //AssetData
